name: 'Git Changelog GitHub Release'
description: 'Drafts release with template using Git Changelog Lib.'
author: 'Tomas Bjerre'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  color: white
  icon: archive
inputs:
  draft:
    required: true
    description: 'If it should be a draft in GitHub or an actual release'
    default: 'true'
  ignoreTagPattern:
    description: |
      Regular expression. Any commit matching it will be ignored.
    required: true
    default: |
      ^\[maven-release-plugin\].*|^\[Gradle Release Plugin\].*|^Merge.*|.*\[GRADLE SCRIPT\].*
  templateDraft:
    description: |
      Used when draft is true.
      Unreleased changes rendered and used as description.
      See https://github.com/tomasbjerre/git-changelog-lib for documentation.
    required: false
    default: |
      {{#tags}}
      {{#ifEquals name "Unreleased"}}
      {{#ifContainsBreaking commits}}
      # 💣 Breaking changes

      {{#commits}}
      {{#ifCommitBreaking .}}
      - {{#eachCommitScope .}} **{{.}}** {{/eachCommitScope}} {{{commitDescription .}}} ([{{subString hash 0 5}}](https://github.com/{{ownerName}}/{{repoName}}/commit/{{hash}}) {{authorName}}) {{#eachCommitRefs .}}{{#ifMatches . "^#[0-9]+"}} [{{.}}](https://github.com/{{ownerName}}/{{repoName}}/issues/{{subString . 1}}) {{/ifMatches}}{{/eachCommitRefs}} {{#eachCommitFixes .}}{{#ifMatches . "^#[0-9]+"}} [{{.}}](https://github.com/{{ownerName}}/{{repoName}}/issues/{{subString . 1}}) {{/ifMatches}}{{/eachCommitFixes}}
      {{/ifCommitBreaking}}
      {{/commits}}

      {{/ifContainsBreaking}}
      {{#ifContainsType commits type='feat'}}
      # 🚀 Features

      {{#commits}}
      {{#ifCommitType . type='feat'}}
      - {{#eachCommitScope .}} **{{.}}** {{/eachCommitScope}} {{{commitDescription .}}} ([{{subString hash 0 5}}](https://github.com/{{ownerName}}/{{repoName}}/commit/{{hash}}) {{authorName}}) {{#eachCommitRefs .}}{{#ifMatches . "^#[0-9]+"}} [{{.}}](https://github.com/{{ownerName}}/{{repoName}}/issues/{{subString . 1}}) {{/ifMatches}}{{/eachCommitRefs}} {{#eachCommitFixes .}}{{#ifMatches . "^#[0-9]+"}} [{{.}}](https://github.com/{{ownerName}}/{{repoName}}/issues/{{subString . 1}}) {{/ifMatches}}{{/eachCommitFixes}}
      {{/ifCommitType}}
      {{/commits}}

      {{/ifContainsType}}
      {{#ifContainsType commits type='fix'}}
      # 🐛 Bug Fixes

      {{#commits}}
      {{#ifCommitType . type='fix'}}
      - {{#eachCommitScope .}} **{{.}}** {{/eachCommitScope}} {{{commitDescription .}}} ([{{subString hash 0 5}}](https://github.com/{{ownerName}}/{{repoName}}/commit/{{hash}}) {{authorName}}) {{#eachCommitRefs .}}{{#ifMatches . "^#[0-9]+"}} [{{.}}](https://github.com/{{ownerName}}/{{repoName}}/issues/{{subString . 1}}) {{/ifMatches}}{{/eachCommitRefs}} {{#eachCommitFixes .}}{{#ifMatches . "^#[0-9]+"}} [{{.}}](https://github.com/{{ownerName}}/{{repoName}}/issues/{{subString . 1}}) {{/ifMatches}}{{/eachCommitFixes}}
      {{/ifCommitType}}
      {{/commits}}

      {{/ifContainsType}}
      {{#ifContainsType commits type='^($|(?!fix|feat|breaking))'}}
      # 🧰 Other changes

      {{#commits}}
      {{#ifCommitType . type='^$'}}
      **{{{messageTitle}}}**

      {{#messageBodyItems}}
      * {{.}} 
      {{/messageBodyItems}}

      [{{subString hash 0 5}}](https://github.com/{{ownerName}}/{{repoName}}/commit/{{hash}}) {{authorName}} *{{commitTime}}*

      {{/ifCommitType}}
      {{/commits}}

      {{/ifContainsType}}
      {{/ifEquals}}
      {{/tags}}
  templateLatestRelease:
    description: |
      Used when draft is false
      Difference between 2 latest tags rendered and used as description.
      See https://github.com/tomasbjerre/git-changelog-lib for documentation.
    required: false
    default: |
      {{#with tags.[0]}}
      {{#ifContainsBreaking commits}}
      # 💣 Breaking changes

      {{#commits}}
      {{#ifCommitBreaking .}}
      - {{#eachCommitScope .}} **{{.}}** {{/eachCommitScope}} {{{commitDescription .}}} ([{{subString hash 0 5}}](https://github.com/{{ownerName}}/{{repoName}}/commit/{{hash}}) {{authorName}}) {{#eachCommitRefs .}}{{#ifMatches . "^#[0-9]+"}} [{{.}}](https://github.com/{{ownerName}}/{{repoName}}/issues/{{subString . 1}}) {{/ifMatches}}{{/eachCommitRefs}} {{#eachCommitFixes .}}{{#ifMatches . "^#[0-9]+"}} [{{.}}](https://github.com/{{ownerName}}/{{repoName}}/issues/{{subString . 1}}) {{/ifMatches}}{{/eachCommitFixes}}
      {{/ifCommitBreaking}}
      {{/commits}}

      {{/ifContainsBreaking}}
      {{#ifContainsType commits type='feat'}}
      # 🚀 Features

      {{#commits}}
      {{#ifCommitType . type='feat'}}
      - {{#eachCommitScope .}} **{{.}}** {{/eachCommitScope}} {{{commitDescription .}}} ([{{subString hash 0 5}}](https://github.com/{{ownerName}}/{{repoName}}/commit/{{hash}}) {{authorName}}) {{#eachCommitRefs .}}{{#ifMatches . "^#[0-9]+"}} [{{.}}](https://github.com/{{ownerName}}/{{repoName}}/issues/{{subString . 1}}) {{/ifMatches}}{{/eachCommitRefs}} {{#eachCommitFixes .}}{{#ifMatches . "^#[0-9]+"}} [{{.}}](https://github.com/{{ownerName}}/{{repoName}}/issues/{{subString . 1}}) {{/ifMatches}}{{/eachCommitFixes}}
      {{/ifCommitType}}
      {{/commits}}

      {{/ifContainsType}}
      {{#ifContainsType commits type='fix'}}
      # 🐛 Bug Fixes

      {{#commits}}
      {{#ifCommitType . type='fix'}}
      - {{#eachCommitScope .}} **{{.}}** {{/eachCommitScope}} {{{commitDescription .}}} ([{{subString hash 0 5}}](https://github.com/{{ownerName}}/{{repoName}}/commit/{{hash}}) {{authorName}}) {{#eachCommitRefs .}}{{#ifMatches . "^#[0-9]+"}} [{{.}}](https://github.com/{{ownerName}}/{{repoName}}/issues/{{subString . 1}}) {{/ifMatches}}{{/eachCommitRefs}} {{#eachCommitFixes .}}{{#ifMatches . "^#[0-9]+"}} [{{.}}](https://github.com/{{ownerName}}/{{repoName}}/issues/{{subString . 1}}) {{/ifMatches}}{{/eachCommitFixes}}
      {{/ifCommitType}}
      {{/commits}}

      {{/ifContainsType}}
      {{#ifContainsType commits type='^($|(?!fix|feat|breaking))'}}
      # 🧰 Other changes

      {{#commits}}
      {{#ifCommitType . type='^$'}}
      **{{{messageTitle}}}**

      {{#messageBodyItems}}
      * {{.}} 
      {{/messageBodyItems}}

      [{{subString hash 0 5}}](https://github.com/{{ownerName}}/{{repoName}}/commit/{{hash}}) {{authorName}} *{{commitTime}}*

      {{/ifCommitType}}
      {{/commits}}

      {{/ifContainsType}}
      {{/with}}
outputs:
  id:
    description: Of created release
  html_url:
    description: Of created release
  upload_url:
    description: Of created release
  version:
    description: Of created release
  description:
    description: That was reated
