name: Draft release

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  call-workflow:
    uses: tomasbjerre/.github/.github/workflows/bundle-npm-action-draft-release.yaml@master
    secrets: inherit
